#!/bin/sh
bspc rule -r "*"

### Start Programs ###
killall "sxhkd"
sxhkd -c $HOME/.config/sxhkd/sxhkdrc-bspwm &
killall "picom"
picom --experimental-backends -b &
killall "feh"
feh --bg-fill ~/wallpapers/nord.png &
killall "polybar"
polybar bar1 &
polybar bar2 &
killall "bspswallow"
bspswallow &
killall "flameshot"
flameshot &

### Monitors ###
bspc monitor DP-0 -d I II III IV V
bspc monitor DP-2 -d VI VII VIII IX X

### Settings ###
bspc config automatic_scheme spiral
bspc config initial_polarity second_child
bspc config pointer_modifier shift
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config gapless_monocle true
bspc config click_to_focus true
bspc config merge_overlapping_monitors true
bspc config pointer_follows_monitor true

bspc config top_padding 30
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 10

bspc config normal_border_color "#2E3440"
bspc config active_border_color "#2E3440"
bspc config focused_border_color "#5E81AC"
bspc config presel_feedback_color "#5E81AC"

### Window rules ###
bspc rule -a Screensaver state=fullscreen
bspc rule -a Notes state=floating
bspc rule -a Firefox:*:Picture-in-Picture sticky=on state=floating
bspc rule -a *:*:"Picture in Picture" sticky=on state=floating
